#!/bin/bash                                                
echo "$1 $2 $3"                                                           
shift 3
echo "$1 $2 $3"

R:
./script10.sh 1 2 3 4 5 6
1 2 3
4 5 6
