#!/bin/bash                                                            
echo -n "Insert text: "                                                          
read VAR                                                            
echo "${#VAR}"

 R: codelearn
 VAR = 9
